source 'https://github.com/TuyaInc/TYPublicSpecs.git'

target 'TYModuleServices_Example' do
  pod 'TYModuleServices', :path => '../'

  target 'TYModuleServices_Tests' do
    inherit! :search_paths

    
  end
end
